version: '3.9'
services:
  app:
    # image q3
    image: ma_super_app
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=dbpassword
      - DATABASE_NAME=dbname
    depends_on:
      - mysql
    ports:
      - "8000:8000"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: mysqlpassword
    ports:
      - "3306:3306"